FROM postgres:16.3-bookworm
# RUN apt-get update && \
# apt-get install -y netcat-openbsd vim
# COPY ./docker-entrypoint.sh /scripts/
# RUN chmod +x /scripts/docker-entrypoint.sh
# ENTRYPOINT ["/scripts/docker-entrypoint.sh"]
