# Generated by Django 5.0.6 on 2024-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.CharField(max_length=50)),
                ('looser', models.CharField(max_length=50)),
                ('score_winner', models.IntegerField()),
                ('score_looser', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
