# Generated by Django 5.0.6 on 2024-10-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='authorized_user',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_by',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
