# Generated by Django 5.0.6 on 2024-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_gen_app', '0002_alter_room_authorized_user_alter_room_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
