filebeat.inputs:
  - type: docker
    containers:
      path: "/var/lib/docker/containers"
      stream: "stdout"
      ids:
        - "*"
      exclude_files: ['\.gz$']
    fields:
      service: "generic-service" # Adicione um campo genérico que será sobrescrito
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: error
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

ssl.verification_mode: none
