# Generated by Django 5.0.6 on 2024-07-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
