# Generated by Django 5.0.6 on 2024-09-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
