# Generated by Django 5.0.6 on 2024-05-29 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_usercredentials_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='username',
            field=models.CharField(default=datetime.datetime(2024, 5, 29, 18, 21, 33, 718834, tzinfo=datetime.timezone.utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
