# Generated by Django 5.0.6 on 2024-05-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_usercredentials_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='username',
        ),
    ]
