# Generated by Django 5.0.6 on 2024-05-31 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_usercredentials_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blockList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friendList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
