# Generated by Django 5.0.6 on 2024-06-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_userprofile_blocklist_userprofile_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='data_expiracao',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='token',
        ),
    ]
