# Generated by Django 5.0.6 on 2024-06-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_remove_usercredentials_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='id',
        ),
    ]
