# Generated by Django 5.0.7 on 2024-07-14 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('friend_list', models.JSONField(default=list)),
                ('blocked_list', models.JSONField(default=list)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('two_factor_code', models.CharField(blank=True, max_length=255, null=True)),
                ('two_factor_expiry', models.DateTimeField(blank=True, null=True)),
                ('two_factor_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('pong_wins', models.IntegerField(default=0)),
                ('pong_losses', models.IntegerField(default=0)),
                ('pong_match_history', models.JSONField(default=list)),
                ('pong_rank', models.IntegerField(default=0)),
                ('snake_wins', models.IntegerField(default=0)),
                ('snake_losses', models.IntegerField(default=0)),
                ('snake_match_history', models.JSONField(default=list)),
                ('snake_rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
