# Generated by Django 5.0.6 on 2024-07-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCredentials',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
