# Generated by Django 5.0.6 on 2024-07-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias_name',
            field=models.TextField(blank=True),
        ),
    ]
