# Generated by Django 5.0.7 on 2024-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userprofile_alias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alias_name',
            field=models.TextField(blank=True),
        ),
    ]
