# Generated by Django 5.0.7 on 2024-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_userprofile_alias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alias_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
