# Generated by Django 5.0.6 on 2024-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
