# Generated by Django 5.0.6 on 2024-07-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blocked_list',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friend_list',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend_list',
            field=models.JSONField(default=list),
        ),
    ]
