# Generated by Django 5.1 on 2024-09-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_userprofile_alias_name_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
