# Generated by Django 5.1 on 2024-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_userprofile_alias_name_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alias_name',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
