# Generated by Django 5.1.1 on 2024-09-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_userprofile_alias_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userApi42',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alias_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
