# Generated by Django 5.1.1 on 2024-09-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userprofile_api_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userApi42',
            field=models.BooleanField(default=False),
        ),
    ]
