# Generated by Django 5.0.6 on 2024-07-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_userprofile_is_otp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_otp_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
