# Generated by Django 5.0.6 on 2024-07-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_userprofile_is_otp_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_otp_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_secret_key',
        ),
    ]
